### ISSUE TITLE
Can this mod overrides resources at the `resourcepacks` folder and solve translation key conflict

### ISSUE THREAD

**Issue by ghost** [glowredman/TX-Loader#4]
I have already put my resources at `./config/txloader/forceload/`,but it didn't override at all.
My resources is a .lang file and I want to use TXLoader to solve translation key conflict(for example two mods both use `tile.mixer` translation key,so when you are using a translation resourcepacks,one of them may override the other).

**Comment by glowredman** [comment]
Do I understand you correnctly that you want to have two blocks to have a different name from each other but they both have the same unlocalized name? In that case you can't use TX Loader for that, nor Resource Loader or any other similar mod because of the way MC handles localizations. You could use Craft Tweaker to change the unlocalized name however and then add the localization via TX Loader.

Otherwise I'd need some more info:
- What MC version are you using?
- If MC 1.7.10: what TX Loader version are you using?
- What other mods do you have installed?
- How is your `./config/txloader/` directory structured?

**Comment by ghost** [comment]
Okay, I see, I'll use Crafttweaker to do this.By the way I'm using 1.12.2.
